import './globals.css';
import * as C from 'src/components';

export const metadata = {
  title: 'EveryGSM',
  description: 'Generated by Themoment',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <C.Nav />
        {children}
      </body>
    </html>
  );
}
