'use client';
import { Metadata } from 'next';
import './globals.css';
import Head from 'next/head';

// export const metadata: Metadata = {
//   title: 'Every GSM',
//   description: 'Generated by Themoment',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <Head>
        <title>Every GSM</title>
        <meta property="og:title" content="Every GSM" key="title" />
      </Head>
      <body>{children}</body>
    </html>
  );
}
