'use client';
import * as C from 'components';
import { useState } from 'react';
import { ThemeProvider } from '@emotion/react';
import { theme, darktheme } from 'styles/theme';
import { NextSeo } from 'next-seo';

function Home() {
  const [isDark, setIsDark] = useState<boolean>(false);
  return (
    <ThemeProvider theme={isDark ? darktheme : theme}>
      <NextSeo
        title="EveryGSM"
        description="Generated by Themoment"
        openGraph={{
          type: 'website',
          url: 'https://every.hellogsm.kr/',
          title: 'EveryGSM',
          description: 'Generated by Themoment',
          images: [
            {
              url: 'https://ifh.cc/g/YmvWVp.png',
              width: 800,
              height: 400,
            },
          ],
        }}
      />
      <C.Nav isDark={isDark} setIsDark={setIsDark} />
      <C.MainContainer isDark={isDark}></C.MainContainer>
      <C.Footer isDark={isDark} />
    </ThemeProvider>
  );
}

export default Home;
